/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        wa: {
          dark: '#075E54',
          teal: '#128C7E',
          light: '#25D366',
          tealDark: '#008069',
          panel: '#F0F2F5',
          panelDark: '#111B21',
          header: '#008069',
          headerDark: '#202C33',
          bubbleOut: '#D9FDD3',
          bubbleOutDark: '#005C4B',
          bubbleIn: '#FFFFFF',
          bubbleInDark: '#202C33',
          chatBg: '#EFEAE2',
          chatBgDark: '#0B141A',
          sidebar: '#FFFFFF',
          sidebarDark: '#111B21',
          hover: '#F5F6F6',
          hoverDark: '#202C33',
          active: '#F0F2F5',
          activeDark: '#2A3942',
          border: '#E9EDEF',
          borderDark: '#222D34',
          text: '#111B21',
          textDark: '#E9EDEF',
          secondary: '#667781',
          secondaryDark: '#8696A0',
          blue: '#53BDEB',
          tick: '#53BDEB',
          yellow: '#FFEB3B',
          amber: '#FFC107',
        },
      },
      fontFamily: {
        sans: ['Cairo', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.18s ease-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'slide-right': 'slideRight 0.22s ease-out',
        'slide-left': 'slideLeft 0.22s ease-out',
        'scale-in': 'scaleIn 0.16s ease-out',
        'pulse-ring': 'pulseRing 1.4s ease-out infinite',
        'wave': 'wave 1s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideRight: { '0%': { transform: 'translateX(100%)' }, '100%': { transform: 'translateX(0)' } },
        slideLeft: { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.96)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        pulseRing: { '0%': { boxShadow: '0 0 0 0 rgba(37,211,102,0.6)' }, '70%': { boxShadow: '0 0 0 8px rgba(37,211,102,0)' }, '100%': { boxShadow: '0 0 0 0 rgba(37,211,102,0)' } },
        wave: { '0%,100%': { transform: 'scaleY(0.4)' }, '50%': { transform: 'scaleY(1)' } },
      },
    },
  },
  plugins: [],
};
